name: robot_lc
channels:
  - pytorch
  - nvidia
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - ffmpeg=4.3
  - filelock=3.17.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.14.0.30
  - libcurand=10.3.10.19
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pip=25.1
  - pysocks=1.7.1
  - python=3.9.21
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==12.0.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - cffi==1.17.1
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - decord==0.6.0
      - deepspeed==0.17.1
      - defusedxml==0.7.1
      - diffusers==0.33.0
      - docopt==0.6.2
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fonttools==4.58.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.3.2
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.16.0
      - hf-xet==1.1.3
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipython==8.12.3
      - isoduration==20.11.0
      - jedi==0.19.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - lightning-utilities==0.14.3
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - moviepy==2.1.2
      - msgpack==1.1.1
      - multidict==6.4.4
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.11.1.4
      - notebook==7.4.1
      - notebook-shim==0.2.4
      - nvidia-ml-py==12.575.51
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - overrides==7.7.0
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.15.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pipdeptree==2.26.1
      - pipreqs==0.5.0
      - platformdirs==4.3.7
      - proglog==0.1.11
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - pytorch-lightning==2.5.1
      - pyzmq==26.4.0
      - referencing==0.36.2
      - regex==2024.11.6
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torchmetrics==1.7.3
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.48.1
      - types-python-dateutil==2.9.0.20241206
      - typing-inspection==0.4.1
      - uri-template==1.3.0
      - wandb==0.20.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - yarg==0.1.9
      - yarl==1.20.1
      - zipp==3.21.0
